### ISSUE TITLE
Text where it shouldn't be

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#4]
**bug**
While trying the different languages I found some strange text behind some words in the Russian language setting screen.

**Screenshots**
![IMG_0842](https://github.com/steel97/veil_wallet/assets/46406370/c974e362-85da-4b55-8ab4-f690896144eb)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS
 - Version 17.1.1

**Comment by steel97** [comment]
Thanks for report! This label should be rendered in single line (I think this caused by too big font), for sure that shouldn't happend for accessibility reasons. However not sure if it's issue in my code or in flutter framework, need some time to investigate it (this is my first flutter project so I'am not too confident in how to build layouts in right way)

**Comment by steel97** [comment]
@ohcee I made few changes to settings UI, so text should not overflow single line anymore
