### ISSUE TITLE
macOS wallet cannot connect to node

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#7]
**bug**
Wallet cannot connect to network

**Expected behavior**
Was trying to make and/or import a wallet and got this error each time. 

**Screenshots**
![Screenshot 2023-11-19 at 8 36 10 PM](https://github.com/steel97/veil_wallet/assets/46406370/d11d9aeb-e31e-419c-aa0e-c52969d6630c)

**Desktop**
 - OS: MacOS
 - Version: Sonoma 14.1

**Comment by steel97** [comment]
I'am surprised that wallet even able to start on MacOS😅
I failed to start it on mac mini 2009 (MacOS Monterey), need some time to investigate and fix

**Comment by steel97** [comment]
@ohcee yesterday I finally able to update my old mac to Sonoma and installed XCode, unfortunately I still not able to start wallet (the reason why wallet can't be launched on old macs is that flutter requires Metal API to render UI, which is not supported on macs before 2012).
The good news is that at least now I can experiment with entitlement files (which is very difficult to edit without XCode) and I suppose the roots of the issue is permissions (need to figure out which permissions required to run wallet app).
By the way, could you please check whether wallet requires Rosetta or current binary is universal and can be launched on M1 natively?
I also temporarily added exception string to the error message, could you please run wallet again (with latest automated build from actions tab) and see what error it shows now?
Thanks in advance!

**Comment by ohcee** [comment]
@steel97 I tried to use the new version and I couldn't get it to open. I had to ignore and allow a lot of thing that were flagged by the security but still not able to open this version. So trying to launch with M1 didn't work this time. I could attempt more things a bit later.

**Comment by steel97** [comment]
@ohcee thanks for testing! Actually I didn't made too much changes related to macos, very strange that it fails to start... (not sure from which commit we should count changes...  https://github.com/steel97/veil_wallet/compare/5bb9a6e3dece5a3ac9ad233b2e4fb060be165f89...main ).

Regarding github actions, it fails on android step because release signing key is not set on your fork. Still, good point, need to think about workaround (maybe if release signing key not set, actions should produce debug build)

**Comment by ohcee** [comment]
I could try again when I get back to my desk. I remember having to allow a bunch of things through last time but it worked then maybe I did something different.

**Comment by steel97** [comment]
@ohcee I made some changes to github actions, you could try it. Now it's possible to manually launch build action (for any branch). Also, I made a conditional build for android target, so now release signing key can be ignored.
![screenshot](https://github.com/steel97/veil_wallet/assets/7414151/d250130a-282a-4ef7-bbe0-28a88e884543)

**Comment by ohcee** [comment]
@steel97 I'm having a lot of issues trying to get it working on macOS. Kinda makes me wonder if i use the ios version or something. I was messing around when I was trying it. I'm going to keep trying an I'll let you know if anything else changes.

**Comment by ohcee** [comment]
Also a bit different error message but still the same. This time I tested the Linux version as well and it did what the macOS did the time I got it to work. Couldn't connect to node. When I pressed the bio metric nothing happened. I was able to enter a seed phrase but only go to this screen. 
![Screenshot from 2023-11-30 21-14-21](https://github.com/steel97/veil_wallet/assets/46406370/104fad01-b9fe-4d00-a031-428b505eb10c)

**Comment by steel97** [comment]
@ohcee on linux error makes sense, it happened due to wallet was unable to write mnemonic to encrypted storage (maybe linux distro missing some required libraries, like [libsecret](https://wiki.gnome.org/Projects/Libsecret). Github actions compile linux version with `ubuntu-latest` runner which is now equal to `ubuntu 22.04`, so this version is minimum required version to run wallet (however I'am thinking to set it to 20.04 to increase compatibility).
Also flatpak/snap is on my TO-DO list, so it would be less painful to run wallet on linux.

**Comment by steel97** [comment]
I think macos version also doesn't have access to secure storage (keychain), that's why it fail, need to investigate more

**Comment by steel97** [comment]
just tested on ubuntu, there was issue with `flutter_secure_storage` (it works slightly different from windows version), I made fix so now wallet should work on linux.

**Comment by ohcee** [comment]
Good work on all this.

 I think you might be on to something with the (keychain) I did have several pop ups about a (keychain) when I was trying to get the macOS version working. 

I've tested the Linux again and it working! A few small bugs but working great. (I'll add those bug issues soon).

**Comment by steel97** [comment]
Actually after linux fix, macos might also work (if it's possible to launch somehow).
MacOS probably doesn't like unsigned binaries, and I can't sign it because I'am not enrolled in apple developer progam (which requires yearly payment)...
However, if you compile wallet locally you can pass signature check (according to https://stackoverflow.com/a/63157844, some more info https://stackoverflow.com/a/70518397)

**Comment by ohcee** [comment]
We need to get you enrolled.

**Comment by steel97** [comment]
For sure, but that would be later, when veil price grow a little

**Comment by steel97** [comment]
> @steel97 I'm having a lot of issues trying to get it working on macOS. Kinda makes me wonder if i use the ios version or something. I was messing around when I was trying it. I'm going to keep trying an I'll let you know if anything else changes.

Found some info while looking through repositories which I starred:
![screen](https://github.com/steel97/veil_wallet/assets/7414151/77569d28-0d61-481c-a85f-52a21b4a42ea)
https://github.com/TokisanGames/Terrain3D/releases/tag/v0.9.0-beta

So as I mentioned before, root of those issues is binaries signing.Seems that building from sources will allow to bypass this limitations

**Comment by ohcee** [comment]
I could try and mess around later today. I would be really nice to a easy to use mac version.

**Comment by ohcee** [comment]
Ok some news. I got the wallet built and opened. But when trying to import or start a new wallet I would enter the words and click and press enter and nothing would happen. 

The output at the bottom of Xcode was displaying :
![Screenshot 2023-12-20 at 5 12 48 PM](https://github.com/steel97/veil_wallet/assets/46406370/18b42a08-90c0-463f-a8ea-b48beab3fb07).

So I was not able to open the wallet I was stuck at entering the seedphrase. 

Also after running `flutter build macos --release` I was getting this error `d: warning: object file (/Desktop/veil_wallet/build/macos/Build/Products/Release/veil_light_plugin/libveil_light_plugin.a[x86_64][5](compiler_builtins-ff6f68c92d39450d.compiler_builtins.734ba38a573e683a-cgu.000.rcgu.o)) was built for newer 'macOS' version (10.12) than being linked (10.11)`

I was able to change the version to 10.14 and it seemed to work. That's all I got for now.

**Comment by steel97** [comment]
@ohcee this is really helpful info, thanks! From what I see `local_auth` package (used for biometrics) doesn't supported on macos (same as on linux), so I need to remove biometrics from macos build.
Regarding compilation error in release mode - this shouldn't affect much, as it's just warning

**Comment by steel97** [comment]
can you please build with latest commit? I removed biometrics from macos version of wallet
